apiVersion: v1
kind: Secret
metadata:
  name: aws_secret
type: Opaque
data:
  aws_access_key_id: QUtJQTVPSlg0NVdIUlpSWUtOSEc=
  aws_secret_access_key: WXFqR3QwRjVPTkc1TVFCblZCQ3U3cWc3UWkwLzRKZ2FJR3lpTGRyYQ==
  
  
  