apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      app: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        imagePullPolicy: Always
        image: docker.io/tolu1292/udagram-api-feed:v1
        env:
          - name: POSTGRESS_USERNAME
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRESS_USERNAME
          - name: POSTGRESS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRESS_PASSWORD
          - name: POSTGRESS_DB
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRESS_DB
          - name: POSTGRESS_HOST
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: POSTGRESS_HOST
            
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "4096Mi"
          requests:
            cpu: 250m
            memory: "1000Mi"
   
